[package]
name = "casper_spi_wb_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
embedded-hal = "0.2"
packed_struct = "0.10"
thiserror = "1.0"

[dev-dependencies]
spidev = "0.5"
rppal = { version = "0.13", features = ["hal"] }
